'use strict';
// ════════════════════════════════════════════════════════════════════════
// goal-plans/taxonomy.js — frozen 24-goal catalog (v1).
//
// Each entry is a contract: the goal_id is referenced by FE chips, the AI
// prompt builder, reminder templates, and follow-up suggestions. Adding
// a goal = bump catalog version (V2) and write new test fixtures.
//
// Every entry MUST have:
//   - id (snake_case slug)
//   - area (one of AREAS in constants.js)
//   - domains[] (which agent areas it touches — metadata only)
//   - display: { en, es, fr, de, pt, ru }
//   - default_duration
//   - inputs_required[] / inputs_optional[]
//   - research_anchor (1-line citation, plain text)
//   - why_this_works: { en, ... } (2 short sentences, citation-grade)
//   - item_archetypes[] (kinds the LLM may include — informs prompt)
//   - fallback_items[] (used when LLM fails — items shape from types.js)
// ════════════════════════════════════════════════════════════════════════

const TAXONOMY = [
  // ──────────── WEIGHT (4) ────────────
  {
    id: 'lose_weight_moderate', area: 'weight',
    domains: ['nutrition', 'fitness'],
    display: {
      en: 'Lose 3–5 kg over 30 days',
      es: 'Bajar 3–5 kg en 30 días',
      fr: 'Perdre 3 à 5 kg en 30 jours',
      de: '3–5 kg in 30 Tagen abnehmen',
      pt: 'Perder 3–5 kg em 30 dias',
      ru: 'Сбросить 3–5 кг за 30 дней',
    },
    default_duration: 30,
    inputs_required: ['current_weight_kg'],
    inputs_optional: ['target_weight_kg', 'start_date', 'cannot_do'],
    research_anchor: 'Hall et al. 2011, The Lancet — energy balance model; ~500 kcal/day deficit ≈ 0.5 kg/week safe loss.',
    why_this_works: {
      en: 'A ~500 kcal/day deficit produces ~0.5 kg/week of fat loss safely. The plan pairs a calorie cap with a protein floor so what you lose is mostly fat, not muscle.',
      es: 'Un déficit diario de ~500 kcal produce ~0,5 kg/semana de pérdida segura. El plan combina un tope calórico con un mínimo de proteína para conservar masa muscular.',
      fr: 'Un déficit d’environ 500 kcal/jour entraîne ~0,5 kg/semaine de perte sûre. Le plan associe un plafond calorique et un seuil protéique pour préserver le muscle.',
      de: 'Ein Defizit von ~500 kcal/Tag führt zu ~0,5 kg/Woche sicherem Fettverlust. Der Plan kombiniert Kaloriendeckel und Eiweißbasis, damit Muskeln erhalten bleiben.',
      pt: 'Um déficit diário de ~500 kcal gera ~0,5 kg/semana de perda segura. O plano combina teto calórico e piso proteico para preservar massa muscular.',
      ru: 'Дефицит ~500 ккал/день даёт ~0,5 кг/нед безопасной потери. План объединяет потолок калорий и норму белка, чтобы сохранить мышцы.',
    },
    item_archetypes: ['cap', 'hit', 'do', 'time'],
    fallback_items: [
      { id: 'kcal_cap',    title: 'Eat ≤ 1,650 kcal',                target: 1650, unit: 'kcal', kind: 'cap' },
      { id: 'protein_min', title: 'Hit ≥ 110 g protein',             target: 110,  unit: 'g',    kind: 'hit' },
      { id: 'walk_30',     title: '30-min brisk walk after lunch',   target: 30,   unit: 'min',  kind: 'do', time_anchor_local: '13:30' },
      { id: 'water_2l',    title: 'Drink ≥ 2.5 L water',             target: 2500, unit: 'ml',   kind: 'hit' },
      { id: 'lights_out',  title: 'Lights out by 11:15 pm',          unit: '',     kind: 'time', time_anchor_local: '23:15' },
    ],
  },
  {
    id: 'stop_snacking', area: 'weight',
    domains: ['nutrition'],
    display: {
      en: 'Cut evening snacking', es: 'Cortar el picoteo nocturno',
      fr: 'Stopper le grignotage du soir', de: 'Abendliches Snacken stoppen',
      pt: 'Cortar beliscos noturnos', ru: 'Прекратить вечерние перекусы',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: ['trigger_time'],
    research_anchor: 'Tribole & Resch 2020 — Intuitive Eating; satiety architecture beats restriction.',
    why_this_works: {
      en: 'Most night snacking is an underfed daytime in disguise. Anchoring a protein-rich dinner and a calming wind-down beats willpower.',
      es: 'Casi todo picoteo nocturno es un día subalimentado disfrazado. Una cena con proteína y un cierre tranquilo gana a la fuerza de voluntad.',
      fr: 'Le grignotage nocturne est souvent une journée sous-alimentée déguisée. Un dîner protéiné et une routine apaisante battent la volonté.',
      de: 'Nächtliches Snacken ist meist ein unterversorgter Tag in Verkleidung. Eine proteinreiche Hauptmahlzeit und eine ruhige Routine schlagen Willenskraft.',
      pt: 'Beliscos noturnos costumam ser um dia subalimentado disfarçado. Jantar com proteína e ritual de descanso vencem força de vontade.',
      ru: 'Ночные перекусы — обычно недоеденный день. Ужин с белком и спокойный вечер сильнее силы воли.',
    },
    item_archetypes: ['hit', 'do', 'skip', 'time'],
    fallback_items: [
      { id: 'dinner_protein', title: 'Dinner has ≥ 30 g protein', target: 30, unit: 'g', kind: 'hit' },
      { id: 'tea_wind_down',  title: 'Decaf herbal tea at 9 pm', kind: 'do', time_anchor_local: '21:00' },
      { id: 'no_screen_food', title: 'No food in front of screens', kind: 'skip' },
      { id: 'lights_out',     title: 'Lights out by 11:00 pm', kind: 'time', time_anchor_local: '23:00' },
    ],
  },
  {
    id: 'smaller_portions', area: 'weight',
    domains: ['nutrition'],
    display: {
      en: 'Smaller portions, same foods', es: 'Porciones más pequeñas, misma comida',
      fr: 'Portions plus petites, mêmes plats', de: 'Kleinere Portionen, gleiches Essen',
      pt: 'Porções menores, mesma comida', ru: 'Меньшие порции, та же еда',
    },
    default_duration: 30,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Wansink 2006, Mindless Eating; plate-size + serving-cue heuristics reduce intake ~15–20%.',
    why_this_works: {
      en: 'You don’t need new foods, just new portions. Small plate + half-fill cues cut intake 15–20% without hunger.',
      es: 'No necesitas comidas nuevas, solo porciones nuevas. Plato pequeño + media porción reducen ingesta 15–20% sin hambre.',
      fr: 'Pas besoin de nouveaux plats, juste de nouvelles portions. Petite assiette + demi-portion réduisent l’apport de 15–20% sans faim.',
      de: 'Keine neuen Speisen nötig, nur neue Portionen. Kleiner Teller und halbe Füllung senken die Aufnahme um 15–20% ohne Hunger.',
      pt: 'Não precisa de pratos novos, só porções novas. Prato pequeno + meia porção reduzem ingestão 15–20% sem fome.',
      ru: 'Не нужны новые блюда — только новые порции. Маленькая тарелка и половина дают −15–20% без голода.',
    },
    item_archetypes: ['cap', 'do'],
    fallback_items: [
      { id: 'small_plate',    title: 'Eat off a small plate',   kind: 'do' },
      { id: 'half_carbs',     title: 'Halve your carbs portion', kind: 'cap' },
      { id: 'leave_two',      title: 'Leave 2 bites on every plate', kind: 'do' },
      { id: 'water_first',    title: 'Glass of water before each meal', kind: 'hit', target: 3, unit: 'glasses' },
    ],
  },
  {
    id: 'reduce_sugar', area: 'weight',
    domains: ['nutrition'],
    display: {
      en: 'Cut added sugar', es: 'Reducir azúcar añadido', fr: 'Réduire le sucre ajouté',
      de: 'Zugesetzten Zucker reduzieren', pt: 'Reduzir açúcar adicionado', ru: 'Сократить добавленный сахар',
    },
    default_duration: 30,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Te Morenga et al. 2013, BMJ — added-sugar intake ↔ body weight, dose-response.',
    why_this_works: {
      en: 'Added sugar is the easiest 100–200 daily kcal to cut. Swapping sweet drinks first does most of the work.',
      es: 'El azúcar añadido es las 100–200 kcal diarias más fáciles de quitar. Cambiar bebidas dulces hace casi todo.',
      fr: 'Le sucre ajouté est le plus simple 100–200 kcal/jour à enlever. Remplacer les boissons sucrées fait l’essentiel.',
      de: 'Zugesetzter Zucker sind die einfachsten 100–200 kcal pro Tag. Süßgetränke zuerst zu ersetzen, leistet das Meiste.',
      pt: 'Açúcar adicionado é a forma mais fácil de cortar 100–200 kcal/dia. Trocar bebidas doces resolve a maior parte.',
      ru: 'Добавленный сахар — самые лёгкие 100–200 ккал в день. Сначала уберите сладкие напитки.',
    },
    item_archetypes: ['cap', 'skip', 'hit'],
    fallback_items: [
      { id: 'no_sweet_drinks', title: 'No sweetened drinks today', kind: 'skip' },
      { id: 'fruit_window',    title: 'Fruit before 4 pm only', kind: 'do', time_anchor_local: '16:00' },
      { id: 'sugar_cap',       title: 'Added sugar ≤ 20 g', target: 20, unit: 'g', kind: 'cap' },
    ],
  },

  // ──────────── ENERGY (3) ────────────
  {
    id: 'afternoon_crash', area: 'energy',
    domains: ['nutrition', 'sleep'],
    display: {
      en: 'Beat the 3 pm crash', es: 'Vencer el bajón de las 3', fr: 'Vaincre le coup de barre de 15h',
      de: 'Das Mittagstief schlagen', pt: 'Vencer a queda das 15h', ru: 'Победить дневной спад',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: ['crash_time'],
    research_anchor: 'Monk 2005, Sleep — post-prandial dip ↔ macro composition + light exposure.',
    why_this_works: {
      en: 'The crash is real, but predictable: a balanced lunch + a 10-min walk + 2 minutes of bright light removes most of it.',
      es: 'El bajón es real pero predecible: comida equilibrada + 10 min de caminata + 2 min de luz brillante lo elimina.',
      fr: 'Le coup de barre est réel mais prévisible : déjeuner équilibré + 10 min de marche + 2 min de lumière vive l’éliminent.',
      de: 'Das Tief ist real, aber vorhersagbar: ausgewogenes Mittagessen + 10 min Spaziergang + 2 min helles Licht beheben es.',
      pt: 'A queda é real mas previsível: almoço equilibrado + 10 min de caminhada + 2 min de luz forte resolvem.',
      ru: 'Спад реален, но предсказуем: сбалансированный обед, 10 мин ходьбы и 2 мин яркого света убирают его.',
    },
    item_archetypes: ['do', 'time', 'hit'],
    fallback_items: [
      { id: 'lunch_balance', title: 'Balanced lunch (protein + fiber + carb)', kind: 'do' },
      { id: 'midday_walk',   title: '10-min outdoor walk after lunch', target: 10, unit: 'min', kind: 'do', time_anchor_local: '13:30' },
      { id: 'bright_light',  title: '2 min near a window at 3 pm', kind: 'do', time_anchor_local: '15:00' },
      { id: 'water_2l',      title: '2 L water by 5 pm', target: 2000, unit: 'ml', kind: 'hit' },
    ],
  },
  {
    id: 'morning_wake', area: 'energy',
    domains: ['sleep'],
    display: {
      en: 'Wake rested in 7 days', es: 'Despertar descansado en 7 días', fr: 'Se réveiller reposé en 7 jours',
      de: 'In 7 Tagen ausgeruht aufwachen', pt: 'Acordar descansado em 7 dias', ru: 'Просыпаться отдохнувшим за 7 дней',
    },
    default_duration: 7,
    inputs_required: ['wake_time_target'], inputs_optional: [],
    research_anchor: 'Edinger et al. 2021, JCSM — sleep-restriction therapy regularises sleep onset/offset.',
    why_this_works: {
      en: 'Sleep wants regularity more than length. Same bedtime ± 30 min, morning sunlight, and a consistent wake time reset the system in days.',
      es: 'Dormir necesita regularidad más que duración. Misma hora ± 30 min, luz solar matutina y un despertar fijo arreglan el sistema en días.',
      fr: 'Le sommeil veut de la régularité plus que de la durée. Coucher ± 30 min, lumière matinale et lever régulier rééquilibrent en quelques jours.',
      de: 'Schlaf braucht Regelmäßigkeit mehr als Dauer. Gleiche Bettzeit ± 30 min, Morgenlicht und feste Aufstehzeit setzen das System in Tagen zurück.',
      pt: 'O sono precisa de regularidade mais que duração. Mesmo horário ± 30 min, luz da manhã e despertar fixo recalibram em dias.',
      ru: 'Сну важна регулярность больше длительности. Тот же отбой ± 30 мин, утренний свет и фиксированный подъём перенастраивают за дни.',
    },
    item_archetypes: ['time', 'do', 'skip'],
    fallback_items: [
      { id: 'wake_anchor',   title: 'Wake at 6:45 am (every day)', kind: 'time', time_anchor_local: '06:45' },
      { id: 'morning_light', title: '10 min outside within 30 min of waking', target: 10, unit: 'min', kind: 'do' },
      { id: 'no_caffeine',   title: 'No caffeine after 2 pm', kind: 'skip', time_anchor_local: '14:00' },
      { id: 'bedtime',       title: 'Lights out by 11:00 pm', kind: 'time', time_anchor_local: '23:00' },
    ],
  },
  {
    id: 'caffeine_taper', area: 'energy',
    domains: ['nutrition', 'sleep'],
    display: {
      en: 'Cut to 1 coffee/day', es: 'Reducir a 1 café al día', fr: 'Réduire à 1 café/jour',
      de: 'Auf 1 Kaffee pro Tag reduzieren', pt: 'Reduzir a 1 café por dia', ru: 'Сократить до 1 кофе в день',
    },
    default_duration: 7,
    inputs_required: ['current_cups'], inputs_optional: [],
    research_anchor: 'Roehrs & Roth 2008, Sleep Med Rev — caffeine half-life 5h; afternoon doses disrupt deep sleep.',
    why_this_works: {
      en: 'Caffeine’s 5-hour half-life means a 4 pm coffee still hits at midnight. Tapering preserves your day and rescues your night.',
      es: 'La vida media de la cafeína es de 5 h: un café a las 16 h sigue activo a medianoche. Reducir gradualmente cuida el día y rescata la noche.',
      fr: 'La demi-vie de la caféine est de 5 h : un café à 16 h agit encore à minuit. La diminuer protège le jour et sauve la nuit.',
      de: 'Koffeins Halbwertszeit von 5 h: ein Kaffee um 16 Uhr wirkt noch um Mitternacht. Reduzieren schützt den Tag und rettet die Nacht.',
      pt: 'A meia-vida da cafeína é 5h: café às 16h ainda age à meia-noite. Reduzir cuida do dia e salva a noite.',
      ru: 'Период полувыведения кофеина — 5 ч: кофе в 16 ч ещё действует в полночь. Снижение бережёт день и спасает ночь.',
    },
    item_archetypes: ['cap', 'time', 'skip'],
    fallback_items: [
      { id: 'cap_one_coffee',  title: 'Max 1 caffeinated coffee', target: 1, unit: 'cup', kind: 'cap' },
      { id: 'before_noon',     title: 'Coffee before noon only', kind: 'time', time_anchor_local: '12:00' },
      { id: 'no_afternoon',    title: 'No caffeine after 2 pm', kind: 'skip', time_anchor_local: '14:00' },
      { id: 'water_swap',      title: 'Glass of water in place of 2nd coffee', kind: 'do' },
    ],
  },

  // ──────────── SLEEP (4) ────────────
  {
    id: 'sleep_deeper', area: 'sleep',
    domains: ['sleep'],
    display: {
      en: 'Deeper sleep in 14 days', es: 'Dormir más profundo en 14 días', fr: 'Sommeil plus profond en 14 jours',
      de: 'Tieferer Schlaf in 14 Tagen', pt: 'Sono mais profundo em 14 dias', ru: 'Глубокий сон за 14 дней',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: ['current_bedtime'],
    research_anchor: 'Walker 2017, Why We Sleep — slow-wave sleep responds to temperature, alcohol, and timing cues.',
    why_this_works: {
      en: 'Deep sleep responds to three levers: cool bedroom, last-meal-by-8pm, and no alcohol in the 3 hours before bed. Pull all three and the depth follows.',
      es: 'El sueño profundo responde a tres palancas: dormitorio fresco, última comida antes de las 20h y sin alcohol 3 h antes de acostarse. Tira de las tres y la profundidad llega.',
      fr: 'Le sommeil profond répond à trois leviers : chambre fraîche, dernier repas avant 20h, et pas d’alcool 3h avant le coucher.',
      de: 'Tiefschlaf reagiert auf drei Hebel: kühles Schlafzimmer, letzte Mahlzeit vor 20 Uhr, kein Alkohol in den 3 Stunden vor dem Schlaf.',
      pt: 'O sono profundo responde a três alavancas: quarto fresco, última refeição antes das 20h e sem álcool 3h antes de dormir.',
      ru: 'Глубокий сон зависит от трёх рычагов: прохладная спальня, последняя еда до 20:00, никакого алкоголя за 3 ч до сна.',
    },
    item_archetypes: ['skip', 'time', 'do'],
    fallback_items: [
      { id: 'cool_room',    title: 'Bedroom 18–20°C', kind: 'do' },
      { id: 'last_meal_8',  title: 'Last meal by 8 pm', kind: 'time', time_anchor_local: '20:00' },
      { id: 'no_alcohol_3', title: 'No alcohol 3 h before bed', kind: 'skip' },
      { id: 'wind_down',    title: '15-min wind-down (book/breath)', target: 15, unit: 'min', kind: 'do', time_anchor_local: '22:30' },
    ],
  },
  {
    id: 'fall_asleep_faster', area: 'sleep',
    domains: ['sleep', 'mind'],
    display: {
      en: 'Fall asleep in <15 min', es: 'Dormirse en <15 min', fr: 'S’endormir en <15 min',
      de: 'In <15 min einschlafen', pt: 'Dormir em <15 min', ru: 'Засыпать за <15 мин',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Edinger et al. 2021, JCSM — stimulus-control + 4-7-8 breathwork shorten sleep onset.',
    why_this_works: {
      en: 'If the body is in bed but the mind is at work, sleep stalls. A consistent pre-sleep ritual + 4-7-8 breathing trains the brain to shut down on cue.',
      es: 'Si el cuerpo está en cama pero la mente sigue activa, el sueño se frena. Una rutina previa + respiración 4-7-8 enseña al cerebro a desconectar.',
      fr: 'Le sommeil cale quand le corps est au lit mais l’esprit au travail. Un rituel pré-sommeil + respiration 4-7-8 entraînent à se déconnecter.',
      de: 'Wenn der Körper im Bett, der Kopf aber arbeitet, stockt der Schlaf. Ein festes Pre-Sleep-Ritual + 4-7-8-Atmung trainieren das Abschalten.',
      pt: 'Se o corpo está na cama mas a mente no trabalho, o sono trava. Ritual pré-sono + respiração 4-7-8 ensinam o cérebro a desligar.',
      ru: 'Если тело в постели, а ум на работе — сон не идёт. Ритуал перед сном + дыхание 4-7-8 учат мозг отключаться.',
    },
    item_archetypes: ['skip', 'do', 'time'],
    fallback_items: [
      { id: 'no_phone_bed',  title: 'No phone in bed', kind: 'skip' },
      { id: 'breath_4_7_8',  title: '4 rounds of 4-7-8 breathing', kind: 'do', target: 4, unit: 'rounds' },
      { id: 'dim_lights',    title: 'Dim lights at 10 pm', kind: 'time', time_anchor_local: '22:00' },
      { id: 'bedtime',       title: 'In bed by 11 pm', kind: 'time', time_anchor_local: '23:00' },
    ],
  },
  {
    id: 'fix_late_nights', area: 'sleep',
    domains: ['sleep', 'mind'],
    display: {
      en: 'Stop scrolling past midnight', es: 'Dejar de hacer scroll después de medianoche',
      fr: 'Arrêter le scroll après minuit', de: 'Kein Scrollen mehr nach Mitternacht',
      pt: 'Parar de rolar passada a meia-noite', ru: 'Перестать листать ленту после полуночи',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Cain & Gradisar 2010 — pre-bed screen use ↔ delayed onset, shorter sleep.',
    why_this_works: {
      en: 'It’s rarely "one more video" — it’s a habit loop. Putting the phone in another room makes the right thing automatic.',
      es: 'Casi nunca es “un video más”: es un bucle. Dejar el móvil en otra habitación hace lo correcto automático.',
      fr: 'Ce n’est presque jamais "encore une vidéo" — c’est une boucle. Mettre le téléphone dans une autre pièce rend le bon choix automatique.',
      de: 'Es ist selten „nur noch ein Video“ — es ist eine Schleife. Das Handy in einem anderen Zimmer macht das Richtige automatisch.',
      pt: 'Quase nunca é "só mais um vídeo": é loop. Deixar o celular em outro cômodo torna o certo automático.',
      ru: 'Это редко «ещё одно видео» — это цикл. Телефон в другой комнате делает правильное автоматическим.',
    },
    item_archetypes: ['skip', 'time', 'do'],
    fallback_items: [
      { id: 'phone_away',    title: 'Phone in another room from 10:30 pm', kind: 'do', time_anchor_local: '22:30' },
      { id: 'book_swap',     title: 'Read 10 pages instead', target: 10, unit: 'pages', kind: 'do' },
      { id: 'no_scroll',     title: 'No social media after 10 pm', kind: 'skip' },
      { id: 'lights_out',    title: 'Lights out by 11 pm', kind: 'time', time_anchor_local: '23:00' },
    ],
  },
  {
    id: 'shift_earlier', area: 'sleep',
    domains: ['sleep'],
    display: {
      en: 'Shift bedtime 60 min earlier', es: 'Adelantar 60 min la hora de dormir',
      fr: 'Avancer le coucher de 60 min', de: 'Bettzeit um 60 min vorziehen',
      pt: 'Adiantar 60 min o horário de dormir', ru: 'Сдвинуть отбой на 60 минут раньше',
    },
    default_duration: 7,
    inputs_required: ['current_bedtime', 'target_bedtime'], inputs_optional: [],
    research_anchor: 'Burgess et al. 2010 — phase-advance of ~15 min/day with morning bright light.',
    why_this_works: {
      en: 'You can’t move bedtime by an hour overnight, but ~15 min/day with morning sunlight shifts the clock cleanly.',
      es: 'No puedes mover la hora una hora de golpe, pero ~15 min/día con luz matutina cambia el reloj sin estrés.',
      fr: 'On ne décale pas le coucher d’une heure d’un coup, mais ~15 min/jour avec lumière matinale recale l’horloge.',
      de: 'Du kannst die Bettzeit nicht über Nacht um eine Stunde verschieben, ~15 min/Tag mit Morgenlicht aber schon.',
      pt: 'Não dá pra adiantar 1 h de uma vez, mas ~15 min/dia com luz matinal recalibra o relógio.',
      ru: 'За ночь час не сместить, но ~15 мин/день с утренним светом мягко двигают часы.',
    },
    item_archetypes: ['time', 'do'],
    fallback_items: [
      { id: 'morning_light', title: '10 min outside within 30 min of waking', target: 10, unit: 'min', kind: 'do' },
      { id: 'no_late_caf',   title: 'No caffeine after 12 pm', kind: 'skip', time_anchor_local: '12:00' },
      { id: 'dim_at_9',      title: 'Dim screens at 9 pm', kind: 'time', time_anchor_local: '21:00' },
      { id: 'tonight_target', title: 'In bed 15 min earlier than yesterday', kind: 'do' },
    ],
  },

  // ──────────── CALM (4) ────────────
  {
    id: 'reduce_stress', area: 'calm',
    domains: ['mind'],
    display: {
      en: 'Less stressed in 14 days', es: 'Menos estrés en 14 días', fr: 'Moins stressé en 14 jours',
      de: 'In 14 Tagen weniger gestresst', pt: 'Menos estresse em 14 dias', ru: 'Меньше стресса за 14 дней',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: ['stressful_window'],
    research_anchor: 'Hofmann et al. 2010 — MBSR meta-analysis; mindfulness ↔ medium effect on anxiety/depression.',
    why_this_works: {
      en: 'Two 5-minute breathwork sessions move the nervous system out of fight-or-flight better than one 30-min one. Daily reps beat duration.',
      es: 'Dos sesiones de 5 min de respiración relajan el sistema nervioso más que una de 30 min. Las repeticiones diarias ganan a la duración.',
      fr: 'Deux séances de 5 min de respiration sortent le système nerveux du stress mieux qu’une seule de 30 min.',
      de: 'Zwei 5-min-Atemübungen bringen das Nervensystem besser aus dem Stressmodus als eine 30-min-Sitzung.',
      pt: 'Duas sessões de respiração de 5 min tiram o sistema nervoso do "luta-fuga" melhor que uma de 30 min.',
      ru: 'Две 5-минутные практики дыхания выводят нервную систему из тревоги лучше одной 30-минутной.',
    },
    item_archetypes: ['do', 'time'],
    fallback_items: [
      { id: 'breath_morning', title: '5-min box breathing', target: 5, unit: 'min', kind: 'do', time_anchor_local: '08:30' },
      { id: 'breath_evening', title: '5-min box breathing', target: 5, unit: 'min', kind: 'do', time_anchor_local: '21:00' },
      { id: 'walk_no_phone',  title: '15-min walk without phone', target: 15, unit: 'min', kind: 'do' },
    ],
  },
  {
    id: 'calmer_evenings', area: 'calm',
    domains: ['mind', 'sleep'],
    display: {
      en: 'Wind-down routine', es: 'Rutina de descanso', fr: 'Routine de décompression',
      de: 'Abend-Routine zum Runterkommen', pt: 'Ritual de relaxamento', ru: 'Ритуал расслабления',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'NSF 2015 Sleep in America Poll — consistent pre-sleep routines ↔ subjective sleep quality.',
    why_this_works: {
      en: 'The brain calms on cue when the same 3–4 things happen before bed. The order matters more than the activities.',
      es: 'El cerebro se calma cuando ocurren las mismas 3-4 cosas antes de dormir. El orden importa más que las actividades.',
      fr: 'Le cerveau se calme quand les 3-4 mêmes choses arrivent avant le coucher. L’ordre compte plus que les activités.',
      de: 'Das Gehirn beruhigt sich, wenn dieselben 3–4 Dinge vor dem Bett passieren. Reihenfolge zählt mehr als Aktivitäten.',
      pt: 'O cérebro acalma quando as mesmas 3–4 coisas acontecem antes de dormir. A ordem importa mais que as atividades.',
      ru: 'Мозг успокаивается, когда 3–4 одинаковых действия повторяются перед сном. Порядок важнее самих действий.',
    },
    item_archetypes: ['time', 'do'],
    fallback_items: [
      { id: 'dim_lights',   title: 'Dim lights at 9:30 pm', kind: 'time', time_anchor_local: '21:30' },
      { id: 'tea_ritual',   title: 'Herbal tea', kind: 'do' },
      { id: 'tidy_5',       title: '5-min tidy', target: 5, unit: 'min', kind: 'do' },
      { id: 'lights_out',   title: 'Lights out by 11 pm', kind: 'time', time_anchor_local: '23:00' },
    ],
  },
  {
    id: 'focus_better', area: 'calm',
    domains: ['mind'],
    display: {
      en: 'Sharper focus daily', es: 'Mejor concentración diaria', fr: 'Plus de concentration chaque jour',
      de: 'Schärferer Fokus jeden Tag', pt: 'Foco mais nítido todo dia', ru: 'Острее фокус каждый день',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: ['focus_window'],
    research_anchor: 'Killingsworth & Gilbert 2010, Science — a wandering mind is an unhappy mind; attention training measurable in days.',
    why_this_works: {
      en: 'Focus is a muscle. One 25-minute deep block + a 5-minute walk breaks the day into something the brain can repeat.',
      es: 'La concentración es un músculo. Un bloque de 25 min + caminata de 5 min crean un patrón que el cerebro repite.',
      fr: 'La concentration est un muscle. Un bloc de 25 min + 5 min de marche créent un schéma que le cerveau reproduit.',
      de: 'Fokus ist ein Muskel. Ein 25-Min-Block + 5-Min-Spaziergang schaffen ein Muster, das das Gehirn wiederholt.',
      pt: 'Foco é músculo. Um bloco de 25 min + 5 min de caminhada criam um padrão que o cérebro repete.',
      ru: 'Фокус — это мышца. Блок 25 мин + 5 мин ходьбы создают паттерн, который мозг повторяет.',
    },
    item_archetypes: ['do', 'skip', 'time'],
    fallback_items: [
      { id: 'deep_block',     title: '25-min deep work block', target: 25, unit: 'min', kind: 'do' },
      { id: 'walk_after',     title: '5-min walk after the block', target: 5, unit: 'min', kind: 'do' },
      { id: 'no_socials_am',  title: 'No social media until 11 am', kind: 'skip', time_anchor_local: '11:00' },
    ],
  },
  {
    id: 'breathwork_daily', area: 'calm',
    domains: ['mind'],
    display: {
      en: '4-7-8 daily', es: 'Respiración 4-7-8 diaria', fr: 'Respiration 4-7-8 quotidienne',
      de: '4-7-8 täglich', pt: 'Respiração 4-7-8 diária', ru: 'Дыхание 4-7-8 каждый день',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Russo et al. 2017, Breathe — slow nasal breathing ↔ vagal tone ↑.',
    why_this_works: {
      en: 'Breathing is the only autonomic system you can drive manually. 4 rounds, twice a day, anchors the rest of the day to a calmer baseline.',
      es: 'La respiración es el único sistema autónomo que puedes manejar. 4 rondas, 2 veces al día, fijan un punto de partida más calmado.',
      fr: 'La respiration est le seul système autonome que vous pouvez piloter. 4 cycles, deux fois/jour, ancrent une base plus calme.',
      de: 'Atmung ist das einzige autonome System, das du steuern kannst. 4 Runden, 2× täglich, setzen eine ruhigere Basis.',
      pt: 'Respirar é o único sistema autônomo que dá pra controlar. 4 rodadas, 2× ao dia, fixam uma linha de base mais calma.',
      ru: 'Дыхание — единственная автономная система, которой вы управляете. 4 круга × 2 раза/день дают спокойную базу.',
    },
    item_archetypes: ['do', 'time'],
    fallback_items: [
      { id: 'breath_am', title: '4 rounds 4-7-8 (morning)', target: 4, unit: 'rounds', kind: 'do', time_anchor_local: '08:00' },
      { id: 'breath_pm', title: '4 rounds 4-7-8 (evening)', target: 4, unit: 'rounds', kind: 'do', time_anchor_local: '21:30' },
      { id: 'walk_no_phone', title: '10-min walk without phone', target: 10, unit: 'min', kind: 'do' },
    ],
  },

  // ──────────── FASTING (3) ────────────
  {
    id: 'start_16_8', area: 'fasting',
    domains: ['fasting'],
    display: {
      en: '7-day 16:8 starter', es: 'Inicio 16:8 de 7 días', fr: 'Démarrage 16:8 sur 7 jours',
      de: '7-Tage 16:8 Einstieg', pt: 'Início 16:8 de 7 dias', ru: '16:8 — старт за 7 дней',
    },
    default_duration: 7,
    inputs_required: ['window_start_hour'], inputs_optional: [],
    research_anchor: 'de Cabo & Mattson 2019, NEJM — time-restricted eating; metabolic switch ~12h post last meal.',
    why_this_works: {
      en: 'Sixteen hours without food puts the body into a clean metabolic switch around hour 12. Easing in over 7 days makes it stick.',
      es: 'Dieciséis horas sin comer activan un cambio metabólico a las ~12 h. Entrar gradualmente en 7 días lo hace duradero.',
      fr: 'Seize heures sans manger déclenchent un changement métabolique vers la 12e heure. Y entrer en 7 jours le rend durable.',
      de: '16 Stunden ohne Nahrung lösen einen sauberen Stoffwechsel-Switch ab Stunde 12 aus. In 7 Tagen einsteigen festigt ihn.',
      pt: 'Dezesseis horas sem comer ativam uma transição metabólica por volta da 12ª h. Entrar em 7 dias fixa o hábito.',
      ru: '16 часов без еды запускают метаболический переключатель к 12-му часу. Вход за 7 дней закрепляет привычку.',
    },
    item_archetypes: ['time', 'hit', 'skip'],
    fallback_items: [
      { id: 'eat_start',   title: 'First meal at 12:00 pm', kind: 'time', time_anchor_local: '12:00' },
      { id: 'eat_stop',    title: 'Last meal by 8:00 pm', kind: 'time', time_anchor_local: '20:00' },
      { id: 'water_floor', title: '2.5 L water during fast', target: 2500, unit: 'ml', kind: 'hit' },
      { id: 'no_late_snack', title: 'No food after 8 pm', kind: 'skip' },
    ],
  },
  {
    id: 'adapt_18_6', area: 'fasting',
    domains: ['fasting'],
    display: {
      en: 'Step up to 18:6', es: 'Pasar a 18:6', fr: 'Passer au 18:6',
      de: 'Auf 18:6 erweitern', pt: 'Avançar para 18:6', ru: 'Перейти на 18:6',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Anton et al. 2018, Obesity — 18h fasts ↔ greater autophagy + insulin sensitivity than 16h.',
    why_this_works: {
      en: 'Two extra hours daily push autophagy higher and insulin sensitivity further. If 16:8 was easy, 18:6 is the next gear.',
      es: 'Dos horas extra al día aumentan autofagia y sensibilidad a la insulina. Si 16:8 fue fácil, 18:6 es el siguiente paso.',
      fr: 'Deux heures supplémentaires augmentent l’autophagie et la sensibilité à l’insuline. Si 16:8 était facile, 18:6 est l’étape suivante.',
      de: 'Zwei Stunden mehr fördern Autophagie und Insulinsensitivität. War 16:8 leicht, ist 18:6 der nächste Schritt.',
      pt: 'Duas horas a mais elevam autofagia e sensibilidade à insulina. Se 16:8 foi fácil, 18:6 é o próximo nível.',
      ru: 'Дополнительные 2 ч повышают аутофагию и чувствительность к инсулину. Если 16:8 даётся легко — 18:6 следующий шаг.',
    },
    item_archetypes: ['time', 'hit'],
    fallback_items: [
      { id: 'eat_start',  title: 'First meal at 1:00 pm', kind: 'time', time_anchor_local: '13:00' },
      { id: 'eat_stop',   title: 'Last meal by 7:00 pm', kind: 'time', time_anchor_local: '19:00' },
      { id: 'water_floor', title: '3 L water during fast', target: 3000, unit: 'ml', kind: 'hit' },
      { id: 'protein_min', title: '30 g protein at first meal', target: 30, unit: 'g', kind: 'hit' },
    ],
  },
  {
    id: 'weekend_long', area: 'fasting',
    domains: ['fasting'],
    display: {
      en: 'One 24h fast/week', es: 'Un ayuno de 24h por semana', fr: 'Un jeûne de 24h par semaine',
      de: 'Ein 24-Stunden-Fasten pro Woche', pt: 'Um jejum de 24h por semana', ru: 'Один 24-часовой пост в неделю',
    },
    default_duration: 7,
    inputs_required: ['fast_day'], inputs_optional: [],
    research_anchor: 'Stekovic et al. 2019, Cell Metabolism — alternate-day fasting trial; cardiometabolic gains in 4 weeks.',
    why_this_works: {
      en: 'A single 24-hour fast per week trims weekly intake meaningfully and gives the system a deeper metabolic reset than daily windows.',
      es: 'Un ayuno semanal de 24 h reduce la ingesta semanal y da un reseteo metabólico más profundo que las ventanas diarias.',
      fr: 'Un jeûne de 24h par semaine réduit l’apport hebdo et offre un reset métabolique plus profond que les fenêtres quotidiennes.',
      de: 'Ein 24-Stunden-Fasten pro Woche senkt die Wochenzufuhr und bringt einen tieferen Stoffwechsel-Reset als tägliche Fenster.',
      pt: 'Um jejum semanal de 24h reduz a ingestão e dá um reset metabólico mais profundo que janelas diárias.',
      ru: 'Один 24-часовой пост в неделю снижает недельный приём и даёт более глубокий метаболический сброс.',
    },
    item_archetypes: ['time', 'hit'],
    fallback_items: [
      { id: 'fast_start', title: 'Fast starts after dinner', kind: 'time', time_anchor_local: '20:00' },
      { id: 'fast_water', title: '3 L water during fast', target: 3000, unit: 'ml', kind: 'hit' },
      { id: 'break_gently', title: 'Break with small protein meal', kind: 'do' },
    ],
  },

  // ──────────── HABITS (6) ────────────
  {
    id: 'hydration_target', area: 'habits',
    domains: ['water'],
    display: {
      en: 'Hit daily water target', es: 'Llegar al objetivo diario de agua',
      fr: 'Atteindre l’objectif quotidien d’eau', de: 'Tageswasserziel erreichen',
      pt: 'Atingir a meta diária de água', ru: 'Достичь дневной нормы воды',
    },
    default_duration: 7,
    inputs_required: ['weight_kg'], inputs_optional: [],
    research_anchor: 'EFSA 2010 — adequate-intake reference values for water (~2.0–2.5 L total fluids).',
    why_this_works: {
      en: 'Hydration runs on rhythm, not willpower. A glass at every meal + a bottle on your desk does ~90% of the work.',
      es: 'La hidratación es ritmo, no fuerza de voluntad. Un vaso en cada comida + una botella en el escritorio hacen el 90%.',
      fr: 'L’hydratation est un rythme, pas une volonté. Un verre à chaque repas + une bouteille sur le bureau font 90% du travail.',
      de: 'Trinken läuft über Rhythmus, nicht Willenskraft. Ein Glas zu jeder Mahlzeit + eine Flasche auf dem Schreibtisch reichen meist.',
      pt: 'Hidratar é ritmo, não força de vontade. Um copo em cada refeição + garrafa na mesa fazem ~90% do trabalho.',
      ru: 'Гидратация — это ритм, а не воля. Стакан к каждому приёму пищи + бутылка на столе делают ~90% работы.',
    },
    item_archetypes: ['hit', 'time', 'do'],
    fallback_items: [
      { id: 'morning_glass', title: 'Glass of water on waking', kind: 'do', time_anchor_local: '07:00' },
      { id: 'each_meal',     title: 'Water glass at each meal', kind: 'hit', target: 3, unit: 'glasses' },
      { id: 'total_2_5l',    title: 'Total 2.5 L by end of day', target: 2500, unit: 'ml', kind: 'hit' },
    ],
  },
  {
    id: 'mobility_daily', area: 'habits',
    domains: ['fitness'],
    display: {
      en: '10-min stretch daily', es: '10 min de estiramiento diario',
      fr: '10 min d’étirement par jour', de: '10-Min Mobility täglich',
      pt: '10 min de alongamento por dia', ru: '10-минутная растяжка каждый день',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Behm et al. 2016 — short daily mobility ↔ injury reduction; consistency over volume.',
    why_this_works: {
      en: 'Ten daily minutes of mobility beats a 60-minute weekend session for joint health. Tiny, often.',
      es: 'Diez minutos diarios de movilidad superan a una sesión de 60 min el fin de semana. Pequeño y frecuente.',
      fr: 'Dix minutes quotidiennes battent une séance d’1h le week-end pour les articulations. Petit, souvent.',
      de: '10 Minuten Mobilität täglich schlagen 60 Min am Wochenende. Klein, dafür oft.',
      pt: 'Dez minutos diários superam uma sessão de 60 min no fim de semana. Pequeno, frequente.',
      ru: '10 минут мобильности каждый день эффективнее часа в выходные. Понемногу, но регулярно.',
    },
    item_archetypes: ['do', 'time'],
    fallback_items: [
      { id: 'mobility_am', title: '10-min mobility', target: 10, unit: 'min', kind: 'do', time_anchor_local: '07:30' },
      { id: 'desk_break',  title: 'Stand + stretch every hour', kind: 'do' },
      { id: 'evening_calf', title: 'Calf + hamstring stretch before bed', target: 3, unit: 'min', kind: 'do', time_anchor_local: '22:30' },
    ],
  },
  {
    id: 'step_3k', area: 'habits',
    domains: ['fitness'],
    display: {
      en: '3,000 extra steps/day', es: '3.000 pasos extra al día',
      fr: '3 000 pas en plus par jour', de: '3.000 zusätzliche Schritte pro Tag',
      pt: '3.000 passos extras por dia', ru: '3 000 дополнительных шагов в день',
    },
    default_duration: 7,
    inputs_required: ['current_steps'], inputs_optional: [],
    research_anchor: 'Saint-Maurice et al. 2020, JAMA — step count ↔ all-cause mortality; ~1k extra/day = ~6% risk drop.',
    why_this_works: {
      en: 'Steps you add are the most underrated leverage in wellness. Three thousand extra a day is doable, measurable, and life-extending.',
      es: 'Sumar pasos es la palanca más infravalorada del bienestar. Tres mil extra son alcanzables, medibles y prolongan la vida.',
      fr: 'Ajouter des pas est le levier le plus sous-estimé. Trois mille de plus sont faisables, mesurables, et allongent la vie.',
      de: 'Mehr Schritte sind der unterschätzteste Wellness-Hebel. 3.000 extra sind machbar, messbar und lebensverlängernd.',
      pt: 'Passos a mais são a alavanca mais subestimada. Três mil extras dão pra fazer, medir e ganhar anos.',
      ru: 'Дополнительные шаги — самый недооценённый рычаг. 3 000 в день реальны, измеримы и продлевают жизнь.',
    },
    item_archetypes: ['hit', 'do'],
    fallback_items: [
      { id: 'walk_am',  title: '15-min morning walk', target: 15, unit: 'min', kind: 'do' },
      { id: 'walk_pm',  title: '15-min evening walk', target: 15, unit: 'min', kind: 'do' },
      { id: 'steps_total', title: '3,000 extra steps over baseline', target: 3000, unit: 'steps', kind: 'hit' },
    ],
  },
  {
    id: 'read_10min', area: 'habits',
    domains: ['mind'],
    display: {
      en: '10 min reading/night', es: '10 min de lectura cada noche',
      fr: '10 min de lecture par soir', de: '10 Min Lesen pro Abend',
      pt: '10 min de leitura toda noite', ru: '10 минут чтения каждый вечер',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Bavishi et al. 2016, SSM — daily book reading ↔ longer survival window vs non-readers.',
    why_this_works: {
      en: 'Ten focused minutes of paper reading is one of the quietest, most underrated boosts to mood and sleep. Anchor it nightly.',
      es: 'Diez minutos enfocados de lectura en papel son uno de los impulsos más silenciosos al ánimo y al sueño.',
      fr: 'Dix minutes de lecture papier sont l’un des coups de pouce les plus discrets pour l’humeur et le sommeil.',
      de: '10 fokussierte Minuten auf Papier sind einer der ruhigsten Booster für Stimmung und Schlaf.',
      pt: 'Dez minutos focados em papel são um dos impulsos mais discretos para humor e sono.',
      ru: '10 сосредоточенных минут на бумаге — один из самых тихих усилителей настроения и сна.',
    },
    item_archetypes: ['do', 'time'],
    fallback_items: [
      { id: 'read_night', title: 'Read 10 min before bed', target: 10, unit: 'min', kind: 'do', time_anchor_local: '22:30' },
      { id: 'phone_away', title: 'Phone out of the bedroom', kind: 'skip' },
      { id: 'paper_only', title: 'Paper or e-ink only (no phone)', kind: 'do' },
    ],
  },
  {
    id: 'gain_muscle_lean', area: 'weight',
    domains: ['fitness', 'nutrition'],
    display: {
      en: 'Lean gain over 30 days', es: 'Ganar masa magra en 30 días',
      fr: 'Prise de masse maigre sur 30 jours', de: 'Schlanker Muskelaufbau in 30 Tagen',
      pt: 'Ganho magro em 30 dias', ru: 'Сухой набор за 30 дней',
    },
    default_duration: 30,
    inputs_required: ['current_weight_kg'], inputs_optional: [],
    research_anchor: 'Aragon & Schoenfeld 2013, JISSN — ~1.6 g/kg protein + progressive overload for muscle gain.',
    why_this_works: {
      en: 'Lean gain wants three pillars: 1.6 g/kg protein, a modest surplus (~250 kcal), and progressive resistance training. Do all three and the scale moves slowly but the mirror moves fast.',
      es: 'Ganar masa magra necesita tres pilares: 1,6 g/kg de proteína, leve superávit (~250 kcal) y entrenamiento progresivo.',
      fr: 'La prise de muscle veut 3 piliers : 1,6 g/kg de protéines, un léger surplus (~250 kcal), et un entraînement progressif.',
      de: 'Aufbau braucht 3 Säulen: 1,6 g/kg Eiweiß, leichter Überschuss (~250 kcal), progressives Training.',
      pt: 'Ganho magro pede 3 pilares: 1,6 g/kg de proteína, leve superávit (~250 kcal) e treino progressivo.',
      ru: 'Сухой набор требует трёх опор: 1,6 г/кг белка, лёгкий профицит (~250 ккал) и прогрессивный тренинг.',
    },
    item_archetypes: ['hit', 'do', 'cap'],
    fallback_items: [
      { id: 'protein_floor', title: 'Hit ≥ 130 g protein', target: 130, unit: 'g', kind: 'hit' },
      { id: 'kcal_target',   title: 'Eat ~2,400 kcal', target: 2400, unit: 'kcal', kind: 'cap' },
      { id: 'lift_session',  title: '45-min resistance session', target: 45, unit: 'min', kind: 'do' },
      { id: 'sleep_anchor',  title: 'In bed by 11 pm', kind: 'time', time_anchor_local: '23:00' },
    ],
  },
  {
    id: 'hangover_reset', area: 'energy',
    domains: ['nutrition', 'sleep'],
    display: {
      en: '7-day alcohol pause reset', es: 'Pausa de alcohol de 7 días',
      fr: 'Pause alcool de 7 jours', de: '7-Tage Alkoholpause',
      pt: 'Pausa de álcool de 7 dias', ru: '7-дневная пауза от алкоголя',
    },
    default_duration: 7,
    inputs_required: [], inputs_optional: [],
    research_anchor: 'Verster 2010, CDARR — even moderate alcohol ↔ next-day sleep architecture disruption.',
    why_this_works: {
      en: 'Even one drink shortens REM sleep and lifts next-day cortisol. Seven days clean is enough to feel the floor lift.',
      es: 'Incluso una bebida acorta el REM y eleva el cortisol del día siguiente. Siete días limpios bastan para notar el suelo.',
      fr: 'Même un verre raccourcit le REM et augmente le cortisol du lendemain. Sept jours sans suffisent pour sentir la différence.',
      de: 'Schon ein Drink kürzt REM und hebt das Cortisol am Folgetag. 7 saubere Tage reichen für spürbare Besserung.',
      pt: 'Mesmo uma dose encurta o REM e eleva o cortisol no dia seguinte. Sete dias limpos bastam para sentir o piso subir.',
      ru: 'Даже один бокал укорачивает REM-сон и поднимает кортизол назавтра. 7 чистых дней — заметная разница.',
    },
    item_archetypes: ['skip', 'hit', 'do'],
    fallback_items: [
      { id: 'no_alcohol',  title: 'No alcohol today', kind: 'skip' },
      { id: 'water_2_5l',  title: '2.5 L water', target: 2500, unit: 'ml', kind: 'hit' },
      { id: 'morning_walk', title: '15-min morning walk', target: 15, unit: 'min', kind: 'do' },
      { id: 'lights_out',  title: 'In bed by 11 pm', kind: 'time', time_anchor_local: '23:00' },
    ],
  },
];

module.exports = TAXONOMY;
